# Generated by Django 2.0.5 on 2018-05-22 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20180522_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='dane',
            name='dzialalnosc_finansowa',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dane',
            name='dzialalnosc_operacyjna',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dane',
            name='przychody',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dane',
            name='rok',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dane',
            name='zysk_brutto',
            field=models.IntegerField(default=0),
        ),
    ]
