# Generated by Django 2.0.5 on 2018-05-22 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20180522_2015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dane',
            name='dzialalnosc_finansowa',
        ),
        migrations.RemoveField(
            model_name='dane',
            name='dzialalnosc_operacyjna',
        ),
        migrations.RemoveField(
            model_name='dane',
            name='przychody',
        ),
        migrations.RemoveField(
            model_name='dane',
            name='zysk_brutto',
        ),
        migrations.RemoveField(
            model_name='dane',
            name='zysk_netto',
        ),
    ]
