# Generated by Django 2.0.5 on 2018-05-22 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20180522_2104'),
    ]

    operations = [
        migrations.CreateModel(
            name='DanePrzychody',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwaP', models.CharField(max_length=200)),
                ('przychody', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DaneRok',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwaR', models.CharField(max_length=200)),
                ('rok', models.IntegerField(default=0)),
            ],
        ),
        migrations.DeleteModel(
            name='Dane',
        ),
    ]
