# Generated by Django 2.0.5 on 2018-05-23 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20180522_2224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dane',
            name='dzialalnosc_finansowa',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='dane',
            name='dzialalnosc_operacyjna',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='dane',
            name='przychody',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='dane',
            name='rok',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='dane',
            name='zysk_brutto',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='dane',
            name='zysk_netto',
            field=models.CharField(max_length=20),
        ),
    ]
